---
title: "republican_bills"
author: "Quinn Muller"
date: "2026-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Turn off scientific notation
options(scipen=999)
```


#load libraries and preliminary data
```{r}
#load libraries
library(tidyverse)
library(janitor)
library(lubridate)

#load republican bills data
republican_bills_2026 <- read.csv("data/republican_bills_2026.csv") %>% clean_names()
republican_bills_2025 <- read.csv("data/republican_bills_2025.csv") %>% clean_names()
republican_bills_2024 <- read.csv("data/republican_bills_2024.csv") %>% clean_names()
republican_bills_2023 <- read.csv("data/republican_bills_2023.csv") %>% clean_names()
republican_bills_2022 <- read.csv("data/republican_bills_2022.csv") %>% clean_names()

```


#Clean up data
```{r}
#add column with political parties of lead sponsor

#FOR 2026
republican_bills_2026 <- republican_bills_2026 %>% 
  mutate(
    sponsor_party = case_when(
        str_detect(sponsor, "Senator Augustine") ~ "Democrat",
        str_detect(sponsor, "Senator Hester") ~ "Democrat",
        str_detect(sponsor, "Senator Kramer") ~ "Democrat",
        str_detect(sponsor, "Senator Kagan") ~ "Democrat",
        str_detect(sponsor, "Senator Simonaire") ~ "Republican",
        str_detect(sponsor, "Senator Brooks") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, A.") ~ "Democrat",
        str_detect(sponsor, "Chair, Education, Energy, and the Environment Committee") ~ "Democrat",
        str_detect(sponsor, "Senator West") ~ "Republican",
        str_detect(sponsor, "Chair, Finance Committee") ~ "Democrat",
        str_detect(sponsor, "Senator Jackson") ~ "Democrat",
        str_detect(sponsor, "Senator Sydnor") ~ "Democrat",
        str_detect(sponsor, "Senator Hayes") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, M.") ~ "Democrat",
        str_detect(sponsor, "Senator Ellis") ~ "Democrat",
        str_detect(sponsor, "Senator Hettleman") ~ "Democrat",
        str_detect(sponsor, "Chair, Budget and Taxation Committee") ~ "Democrat",
        str_detect(sponsor, "Senator McKay") ~ "Republican",
        str_detect(sponsor, "Senator Folden") ~ "Republican",
        str_detect(sponsor, "Senator McCray") ~ "Democrat",
        str_detect(sponsor, "Senator Lam") ~ "Democrat",
        str_detect(sponsor, "Senator Jackson") ~ "Democrat",
        str_detect(sponsor, "Chair, Judicial Proceedings Committee") ~ "Democrat",
        str_detect(sponsor, "Senator Muse") ~ "Democrat",
        str_detect(sponsor, "Senator Carozza") ~ "Republican",
        str_detect(sponsor, "Senator Charles") ~ "Democrat",
        str_detect(sponsor, "Senator Benson") ~ "Democrat",
        str_detect(sponsor, "Senator Watson") ~ "Democrat",
        str_detect(sponsor, "Senator Gile") ~ "Democrat",
        str_detect(sponsor, "Senator Beidle") ~ "Democrat",
        str_detect(sponsor, "Senator Bailey") ~ "Republican",
        str_detect(sponsor, "Senator Hershey") ~ "Republican",
        str_detect(sponsor, "Senator Ready") ~ "Republican",
        str_detect(sponsor, "Senator Henson") ~ "Democrat",
        str_detect(sponsor, "Senator Salling") ~ "Republican",
        str_detect(sponsor, "Senator Waldstreicher") ~ "Democrat",
        str_detect(sponsor, "Senator Lewis Young") ~ "Democrat",
        str_detect(sponsor, "Senator Corderman") ~ "Republican",
        str_detect(sponsor, "President") ~ "Democrat",
        str_detect(sponsor, "Senator Smith") ~ "Democrat",
        str_detect(sponsor, "Senator Love") ~ "Democrat",
        str_detect(sponsor, "Senator Gallion") ~ "Republican",
        str_detect(sponsor, "Senator Attar") ~ "Democrat",
        str_detect(sponsor, "Senator Jennings") ~ "Republican",
        str_detect(sponsor, "Senator King") ~ "Democrat",
        str_detect(sponsor, "Senator Mautz") ~ "Republican",
        str_detect(sponsor, "Senator Guzzone") ~ "Democrat",
        str_detect(sponsor, "Senator Rosapepe") ~ "Democrat",
        str_detect(sponsor, "Senator Zucker") ~ "Democrat",
        str_detect(sponsor, "Senator Harris") ~ "Democrat",
        str_detect(sponsor, "Senator Ferguson") ~ "Democrat",
        str_detect(sponsor, "Senator James") ~ "Democrat",
        str_detect(sponsor, "Senator Feldman") ~ "Democrat",
        str_detect(sponsor, "Senators") ~ "Other",
        str_detect(sponsor, "Delegation") ~ "Other",
        str_detect(sponsor, "Delegate Acevero") ~ "Democrat",
        str_detect(sponsor, "Delegate Adams") ~ "Democrat",
        str_detect(sponsor, "Delegate Addison") ~ "Republican",
        str_detect(sponsor, "Delegate Allen") ~ "Democrat",
        str_detect(sponsor, "Delegate Alston") ~ "Democrat",
        str_detect(sponsor, "Delegate Amprey") ~ "Democrat",
        str_detect(sponsor, "Delegate Anderson") ~ "Republican",
        str_detect(sponsor, "Delegate Arentz") ~ "Republican",
        str_detect(sponsor, "Delegate Arikan") ~ "Republican",
        str_detect(sponsor, "Delegate Bagnall") ~ "Democrat",
        str_detect(sponsor, "Delegate Baker") ~ "Republican",
        str_detect(sponsor, "Delegate Barnes") ~ "Democrat",
        str_detect(sponsor, "Delegate Bartlett") ~ "Democrat",
        str_detect(sponsor, "Delegate Beauchamp") ~ "Republican",
        str_detect(sponsor, "Delegate Behler") ~ "Democrat",
        str_detect(sponsor, "Delegate Bhandari") ~ "Democrat",
        str_detect(sponsor, "Delegate Boafo") ~ "Democrat",
        str_detect(sponsor, "Delegate Bouchat") ~ "Republican",
        str_detect(sponsor, "Delegate Boyce") ~ "Democrat",
        str_detect(sponsor, "Delegate Buckel") ~ "Republican",
        str_detect(sponsor, "Delegate Cardin") ~ "Democrat",
            str_detect(sponsor, "Delegate Chang") ~ "Democrat",
        str_detect(sponsor, "Delegate Charkoudian") ~ "Democrat",
        str_detect(sponsor, "Delegate Chisholm") ~ "Republican",
        str_detect(sponsor, "Delegate Ciliberti") ~ "Republican",
        str_detect(sponsor, "Delegate Clippinger") ~ "Democrat",
        str_detect(sponsor, "Delegate Coley") ~ "Democrat",
        str_detect(sponsor, "Delegate Conaway") ~ "Democrat",
        str_detect(sponsor, "Delegate Crosby") ~ "Democrat",
        str_detect(sponsor, "Delegate Crutchfield") ~ "Democrat",
        str_detect(sponsor, "Delegate Cullison") ~ "Democrat",
        str_detect(sponsor, "Delegate Ebersole") ~ "Democrat",
        str_detect(sponsor, "Delegate Edelson") ~ "Democrat",
        str_detect(sponsor, "Delegate Embry") ~ "Democrat",
        str_detect(sponsor, "Delegate Fair") ~ "Democrat",
        str_detect(sponsor, "Delegate Feldmark") ~ "Democrat",
        str_detect(sponsor, "Delegate Fennell") ~ "Democrat",
        str_detect(sponsor, "Delegate Fisher") ~ "Republican",
        str_detect(sponsor, "Delegate Foley") ~ "Democrat",
        str_detect(sponsor, "Delegate Forbes") ~ "Democrat",
        str_detect(sponsor, "Delegate Fraser-Hidalgo") ~ "Democrat",
        str_detect(sponsor, "Delegate Ghrist") ~ "Republican",
        str_detect(sponsor, "Delegate Grammer") ~ "Republican",
        str_detect(sponsor, "Delegate Griffith") ~ "Republican",
        str_detect(sponsor, "Delegate Guyton") ~ "Democrat",
        str_detect(sponsor, "Delegate Guzzone") ~ "Democrat",
        str_detect(sponsor, "Delegate Harrison") ~ "Democrat",
        str_detect(sponsor, "Delegate Hartman") ~ "Republican",
        str_detect(sponsor, "Delegate Healey") ~ "Democrat",
        str_detect(sponsor, "Delegate Hill") ~ "Democrat",
        str_detect(sponsor, "Delegate Hinebaugh") ~ "Republican",
        str_detect(sponsor, "Delegate Holmes") ~ "Democrat",
        str_detect(sponsor, "Delegate Hornberger") ~ "Republican",
        str_detect(sponsor, "Delegate Howard") ~ "Republican",
        str_detect(sponsor, "Delegate Hutchinson") ~ "Republican",
        str_detect(sponsor, "Delegate Ivey") ~ "Democrat",
        str_detect(sponsor, "Delegate Jacobs") ~ "Republican",
        str_detect(sponsor, "Delegate Johnson, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Johnson, S.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, D.") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaiser") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaufman") ~ "Democrat",
        str_detect(sponsor, "Delegate Kerr") ~ "Democrat",
        str_detect(sponsor, "Delegate Kipke") ~ "Republican",
        str_detect(sponsor, "Delegate Korman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lehman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, R.") ~ "Republican",
        str_detect(sponsor, "Delegate Lopez") ~ "Democrat",
        str_detect(sponsor, "Delegate Mangione") ~ "Republican",
        str_detect(sponsor, "Delegate Martinez") ~ "Democrat",
        str_detect(sponsor, "Delegate McCaskill") ~ "Democrat",
        str_detect(sponsor, "Delegate McComas") ~ "Republican",
        str_detect(sponsor, "Delegate Metzgar") ~ "Republican",
        str_detect(sponsor, "Delegate Miller") ~ "Republican",
        str_detect(sponsor, "Delegate Mireku-North") ~ "Democrat",
        str_detect(sponsor, "Delegate Moon") ~ "Democrat",
        str_detect(sponsor, "Delegate Moreno") ~ "Democrat",
        str_detect(sponsor, "Delegate Morgan, M.") ~ "Republican",
        str_detect(sponsor, "Delegate Morgan, T.") ~ "Republican",
        str_detect(sponsor, "Delegate Nawrocki") ~ "Republican",
        str_detect(sponsor, "Delegate Nkongolo") ~ "Republican",
        str_detect(sponsor, "Delegate Odom") ~ "Democrat",
        str_detect(sponsor, "Delegate Palakovich Carr") ~ "Democrat",
        str_detect(sponsor, "Delegate Pasteur") ~ "Democrat",
        str_detect(sponsor, "Delegate Patterson") ~ "Democrat",
        str_detect(sponsor, "Delegate Pena-Melnyk") ~ "Democrat",
        str_detect(sponsor, "Delegate Phillips") ~ "Democrat",
        str_detect(sponsor, "Delegate Pippy") ~ "Republican",
        str_detect(sponsor, "Delegate Pruski") ~ "Democrat",
        str_detect(sponsor, "Delegate Qi") ~ "Democrat",
        str_detect(sponsor, "Delegate Queen") ~ "Democrat",
        str_detect(sponsor, "Delegate Reilly") ~ "Republican",
        str_detect(sponsor, "Delegate Roberson") ~ "Democrat",
        str_detect(sponsor, "Delegate Roberts") ~ "Democrat",
        str_detect(sponsor, "Delegate Rogers") ~ "Democrat",
        str_detect(sponsor, "Delegate Rose") ~ "Republican",
        str_detect(sponsor, "Delegate Rosenberg") ~ "Democrat",
        str_detect(sponsor, "Delegate Ross") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruff") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruth") ~ "Democrat",
        str_detect(sponsor, "Delegate Sample-Hughes") ~ "Democrat",
        str_detect(sponsor, "Delegate Schindler") ~ "Democrat",
        str_detect(sponsor, "Delegate Schmidt") ~ "Republican",
        str_detect(sponsor, "Delegate Shetty") ~ "Democrat",
        str_detect(sponsor, "Delegate Simmons") ~ "Democrat",
        str_detect(sponsor, "Delegate Simpson") ~ "Democrat",
        str_detect(sponsor, "Delegate Smith") ~ "Democrat",
        str_detect(sponsor, "Delegate Solomon") ~ "Democrat",
        str_detect(sponsor, "Delegate Spiegel") ~ "Democrat",
        str_detect(sponsor, "Delegate Stein") ~ "Democrat",
        str_detect(sponsor, "Delegate Stewart") ~ "Democrat",
        str_detect(sponsor, "Delegate Stinnett") ~ "Democrat",
        str_detect(sponsor, "Delegate Stonko") ~ "Republican",
        str_detect(sponsor, "Delegate Szeliga") ~ "Republican",
        str_detect(sponsor, "Delegate Taveras") ~ "Democrat",
        str_detect(sponsor, "Delegate Taylor") ~ "Democrat",
        str_detect(sponsor, "Delegate Terrasa") ~ "Democrat",
        str_detect(sponsor, "Delegate Toles") ~ "Democrat",
        str_detect(sponsor, "Delegate Tomlinson") ~ "Republican",
        str_detect(sponsor, "Delegate Turner") ~ "Democrat",
        str_detect(sponsor, "Delegate Valderrama") ~ "Democrat",
        str_detect(sponsor, "Delegate Valentine") ~ "Republican",
        str_detect(sponsor, "Delegate Vogel") ~ "Democrat",
        str_detect(sponsor, "Delegate Watson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wells") ~ "Democrat",
        str_detect(sponsor, "Delegate White Holland") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilkins") ~ "Democrat",
        str_detect(sponsor, "Delegate Williams") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wims") ~ "Democrat",
        str_detect(sponsor, "Delegate Wivell") ~ "Republican",
        str_detect(sponsor, "Delegate Wolek") ~ "Democrat",
        str_detect(sponsor, "Delegate Woods") ~ "Democrat",
        str_detect(sponsor, "Delegate Woorman") ~ "Democrat",
        str_detect(sponsor, "Delegate Wu") ~ "Democrat",
        str_detect(sponsor, "Delegate Young") ~ "Democrat",
        str_detect(sponsor, "Delegate Ziegler") ~ "Democrat",
        str_detect(sponsor, "Chair, Environment and Transportation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Economic Matters Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Government, Labor, and Elections Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Health Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judiciary Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Ways and Means Committee") ~ "Democrat",
        str_detect(sponsor, "Speaker") ~ "Democrat",
        .default = "Other"
      ))

#FOR 2025
republican_bills_2025 <- republican_bills_2025 %>% 
  mutate(
    sponsor_party = case_when(
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Budget and Taxation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Economic Matters Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Education, Energy, and the Environment Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Environment and Transportation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Finance Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Health and Government Operations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judicial Proceedings Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judiciary Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Ways and Means Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Delegate Acevero") ~ "Democrat",
        str_detect(sponsor, "Delegate Adams") ~ "Democrat",
        str_detect(sponsor, "Delegate Addison") ~ "Republican",
        str_detect(sponsor, "Delegate Allen") ~ "Democrat",
        str_detect(sponsor, "Delegate Alston") ~ "Democrat",
        str_detect(sponsor, "Delegate Amprey") ~ "Democrat",
        str_detect(sponsor, "Delegate Arentz") ~ "Republican",
        str_detect(sponsor, "Delegate Arikan") ~ "Republican",
        str_detect(sponsor, "Delegate Atterbeary") ~ "Republican",
        str_detect(sponsor, "Delegate Bagnall") ~ "Democrat",
        str_detect(sponsor, "Delegate Baker") ~ "Republican",
        str_detect(sponsor, "Delegate Barnes") ~ "Democrat",
        str_detect(sponsor, "Delegate Bartlett") ~ "Democrat",
        str_detect(sponsor, "Delegate Beauchamp") ~ "Republican",
        str_detect(sponsor, "Delegate Behler") ~ "Democrat",
        str_detect(sponsor, "Delegate Bhandari") ~ "Democrat",
        str_detect(sponsor, "Delegate Boafo") ~ "Democrat",
        str_detect(sponsor, "Delegate Bouchat") ~ "Republican",
        str_detect(sponsor, "Delegate Boyce") ~ "Democrat",
        str_detect(sponsor, "Delegate Buckel") ~ "Republican",
        str_detect(sponsor, "Delegate Cardin") ~ "Democrat",
        str_detect(sponsor, "Delegate Chang") ~ "Democrat",
        str_detect(sponsor, "Delegate Charkoudian") ~ "Democrat",
        str_detect(sponsor, "Delegate Chisholm") ~ "Republican",
        str_detect(sponsor, "Delegate Ciliberti") ~ "Republican",
        str_detect(sponsor, "Delegate Clippinger") ~ "Democrat",
        str_detect(sponsor, "Delegate Conaway") ~ "Democrat",
        str_detect(sponsor, "Delegate Crosby") ~ "Democrat",
        str_detect(sponsor, "Delegate Crutchfield") ~ "Democrat",
        str_detect(sponsor, "Delegate Cullison") ~ "Democrat",
        str_detect(sponsor, "Delegate Davis") ~ "Democrat",
        str_detect(sponsor, "Delegate Ebersole") ~ "Democrat",
        str_detect(sponsor, "Delegate Edelson") ~ "Democrat",
        str_detect(sponsor, "Delegate Embry") ~ "Democrat",
        str_detect(sponsor, "Delegate Fair") ~ "Democrat",
        str_detect(sponsor, "Delegate Feldmark") ~ "Democrat",
        str_detect(sponsor, "Delegate Fennell") ~ "Democrat",
        str_detect(sponsor, "Delegate Fisher") ~ "Republican",
        str_detect(sponsor, "Delegate Foley") ~ "Democrat",
        str_detect(sponsor, "Delegate Forbes") ~ "Democrat",
        str_detect(sponsor, "Delegate Fraser-Hidalgo") ~ "Democrat",
        str_detect(sponsor, "Delegate Ghrist") ~ "Republican",
        str_detect(sponsor, "Delegate Grammer") ~ "Republican",
        str_detect(sponsor, "Delegate Griffith") ~ "Republican",
        str_detect(sponsor, "Delegate Guyton") ~ "Democrat",
        str_detect(sponsor, "Delegate Guzzone") ~ "Democrat",
        str_detect(sponsor, "Delegate Harris") ~ "Democrat",
        str_detect(sponsor, "Delegate Harrison") ~ "Democrat",
        str_detect(sponsor, "Delegate Hartman") ~ "Republican",
        str_detect(sponsor, "Delegate Healey") ~ "Democrat",
        str_detect(sponsor, "Delegate Hill") ~ "Democrat",
        str_detect(sponsor, "Delegate Hinebaugh") ~ "Republican",
        str_detect(sponsor, "Delegate Holmes") ~ "Democrat",
        str_detect(sponsor, "Delegate Hornberger") ~ "Republican",
        str_detect(sponsor, "Delegate Howard") ~ "Republican",
        str_detect(sponsor, "Delegate Hutchinson") ~ "Republican",
        str_detect(sponsor, "Delegate Ivey") ~ "Democrat",
        str_detect(sponsor, "Delegate Jackson") ~ "Democrat",
        str_detect(sponsor, "Delegate Jacobs") ~ "Republican",
        str_detect(sponsor, "Delegate Johnson, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Johnson, S.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, D.") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaiser") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaufman") ~ "Democrat",
        str_detect(sponsor, "Delegate Kerr") ~ "Democrat",
        str_detect(sponsor, "Delegate Kipke") ~ "Republican",
        str_detect(sponsor, "Delegate Korman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lehman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, R.") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, R.") ~ "Republican",
        str_detect(sponsor, "Delegate Lopez") ~ "Democrat",
        str_detect(sponsor, "Delegate Mangione") ~ "Republican",
        str_detect(sponsor, "Delegate Martinez") ~ "Democrat",
        str_detect(sponsor, "Delegate McCaskill") ~ "Democrat",
        str_detect(sponsor, "Delegate McComas") ~ "Republican",
        str_detect(sponsor, "Delegate Metzgar") ~ "Republican",
        str_detect(sponsor, "Delegate Miller") ~ "Republican",
        str_detect(sponsor, "Delegate Mireku-North") ~ "Democrat",
        str_detect(sponsor, "Delegate Moon") ~ "Democrat",
        str_detect(sponsor, "Delegate Moreno") ~ "Democrat",
        str_detect(sponsor, "Delegate Morgan, M.") ~ "Republican",
        str_detect(sponsor, "Delegate Morgan, T.") ~ "Republican",
        str_detect(sponsor, "Delegate Nawrocki") ~ "Republican",
        str_detect(sponsor, "Delegate Nkongolo") ~ "Republican",
        str_detect(sponsor, "Delegate Otto") ~ "Republican",
        str_detect(sponsor, "Delegate Palakovich Carr") ~ "Democrat",
        str_detect(sponsor, "Delegate Pasteur") ~ "Democrat",
        str_detect(sponsor, "Delegate Patterson") ~ "Democrat",
        str_detect(sponsor, "Delegate Pena-Melnyk") ~ "Democrat",
        str_detect(sponsor, "Delegate Phillips") ~ "Democrat",
        str_detect(sponsor, "Delegate Pippy") ~ "Republican",
        str_detect(sponsor, "Delegate Pruski") ~ "Democrat",
        str_detect(sponsor, "Delegate Qi") ~ "Democrat",
        str_detect(sponsor, "Delegate Queen") ~ "Democrat",
        str_detect(sponsor, "Delegate Reilly") ~ "Republican",
        str_detect(sponsor, "Delegate Roberson") ~ "Democrat",
        str_detect(sponsor, "Delegate Roberts") ~ "Democrat",
        str_detect(sponsor, "Delegate Rogers") ~ "Democrat",
        str_detect(sponsor, "Delegate Rose") ~ "Republican",
        str_detect(sponsor, "Delegate Rosenberg") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruff") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruth") ~ "Democrat",
        str_detect(sponsor, "Delegate Sample-Hughes") ~ "Democrat",
        str_detect(sponsor, "Delegate Schindler") ~ "Democrat",
        str_detect(sponsor, "Delegate Schmidt") ~ "Republican",
        str_detect(sponsor, "Delegate Shetty") ~ "Democrat",
        str_detect(sponsor, "Delegate Simmons") ~ "Democrat",
        str_detect(sponsor, "Delegate Simpson") ~ "Democrat",
        str_detect(sponsor, "Delegate Smith") ~ "Democrat",
        str_detect(sponsor, "Delegate Solomon") ~ "Democrat",
        str_detect(sponsor, "Delegate Spiegel") ~ "Democrat",
        str_detect(sponsor, "Delegate Stein") ~ "Democrat",
        str_detect(sponsor, "Delegate Stewart") ~ "Democrat",
        str_detect(sponsor, "Delegate Stonko") ~ "Republican",
        str_detect(sponsor, "Delegate Szeliga") ~ "Republican",
        str_detect(sponsor, "Delegate Taveras") ~ "Democrat",
        str_detect(sponsor, "Delegate Taylor") ~ "Democrat",
        str_detect(sponsor, "Delegate Terrasa") ~ "Democrat",
        str_detect(sponsor, "Delegate Toles") ~ "Democrat",
        str_detect(sponsor, "Delegate Tomlinson") ~ "Republican",
        str_detect(sponsor, "Delegate Valderrama") ~ "Democrat",
        str_detect(sponsor, "Delegate Valentine") ~ "Republican",
        str_detect(sponsor, "Delegate Vogel") ~ "Democrat",
        str_detect(sponsor, "Delegate Watson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wells") ~ "Democrat",
        str_detect(sponsor, "Delegate White Holland") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilkins") ~ "Democrat",
        str_detect(sponsor, "Delegate Williams") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wims") ~ "Democrat",
        str_detect(sponsor, "Delegate Wivell") ~ "Republican",
        str_detect(sponsor, "Delegate Wolek") ~ "Democrat",
        str_detect(sponsor, "Delegate Woods") ~ "Democrat",
        str_detect(sponsor, "Delegate Woorman") ~ "Democrat",
        str_detect(sponsor, "Delegate Wu") ~ "Democrat",
        str_detect(sponsor, "Delegate Young") ~ "Democrat",
        str_detect(sponsor, "Delegate Ziegler") ~ "Democrat",      
        str_detect(sponsor, "President") ~ "Democrat",      
        str_detect(sponsor, "Senator Attar") ~ "Democrat",
        str_detect(sponsor, "Senator Augustine") ~ "Democrat",
        str_detect(sponsor, "Senator Bailey") ~ "Republican",
        str_detect(sponsor, "Senator Beidle") ~ "Democrat",
        str_detect(sponsor, "Senator Benson") ~ "Democrat",
        str_detect(sponsor, "Senator Brooks") ~ "Democrat",
        str_detect(sponsor, "Senator Carozza") ~ "Republican",
        str_detect(sponsor, "Senator Charles") ~ "Democrat",
        str_detect(sponsor, "Senator Corderman") ~ "Republican",
        str_detect(sponsor, "Senator Ellis") ~ "Democrat",
        str_detect(sponsor, "Senator Feldman") ~ "Democrat",
        str_detect(sponsor, "Senator Ferguson") ~ "Democrat",
        str_detect(sponsor, "Senator Folden") ~ "Republican",
        str_detect(sponsor, "Senator Gallion") ~ "Republican",
        str_detect(sponsor, "Senator Gile") ~ "Democrat",
        str_detect(sponsor, "Senator Guzzone") ~ "Democrat",
        str_detect(sponsor, "Senator Hayes") ~ "Democrat",
        str_detect(sponsor, "Senator Henson") ~ "Democrat",
        str_detect(sponsor, "Senator Hershey") ~ "Republican",
        str_detect(sponsor, "Senator Hester") ~ "Democrat",
        str_detect(sponsor, "Senator Hettleman") ~ "Democrat",
        str_detect(sponsor, "Senator Jackson, C.") ~ "Democrat",
        str_detect(sponsor, "Senator Jackson, M.") ~ "Democrat",
        str_detect(sponsor, "Senator James") ~ "Democrat",
        str_detect(sponsor, "Senator Jennings") ~ "Republican",
        str_detect(sponsor, "Senator Kagan") ~ "Democrat",
        str_detect(sponsor, "Senator King") ~ "Democrat",
        str_detect(sponsor, "Senator Klausmeier") ~ "Democrat",
        str_detect(sponsor, "Senator Kramer") ~ "Democrat",
        str_detect(sponsor, "Senator Lam") ~ "Democrat",
        str_detect(sponsor, "Senator Lewis Young") ~ "Democrat",
        str_detect(sponsor, "Senator Love") ~ "Democrat",
        str_detect(sponsor, "Senator Mautz") ~ "Republican",
        str_detect(sponsor, "Senator McCray") ~ "Democrat",
        str_detect(sponsor, "Senator McKay") ~ "Republican",
        str_detect(sponsor, "Senator Muse") ~ "Democrat",
        str_detect(sponsor, "Senator Ready") ~ "Republican",
        str_detect(sponsor, "Senator Rosapepe") ~ "Democrat",
        str_detect(sponsor, "Senator Salling") ~ "Republican",
        str_detect(sponsor, "Senator Simonaire") ~ "Republican",
        str_detect(sponsor, "Senator Smith") ~ "Democrat",
        str_detect(sponsor, "Senator Sydnor") ~ "Democrat",
        str_detect(sponsor, "Senator Waldstreicher") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, A.") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, M.") ~ "Democrat",
        str_detect(sponsor, "Senator Watson") ~ "Democrat",
        str_detect(sponsor, "Senator West") ~ "Republican",
        str_detect(sponsor, "Senator Zucker") ~ "Democrat",
        str_detect(sponsor, "Senators") ~ "Other",
        str_detect(sponsor, "Delegation") ~ "Other",
        str_detect(sponsor, "Speaker") ~ "Democrat",
        .default = "Other"
      ))


#FOR 2024
republican_bills_2024 <- republican_bills_2024 %>% 
  mutate(
    sponsor_party = case_when(
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Budget and Taxation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Economic Matters Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Education, Energy, and the Environment Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Environment and Transportation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Finance Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Health and Government Operations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judicial Proceedings Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judiciary Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Ways and Means Committee") ~ "Democrat",
        str_detect(sponsor, "Delegate Acevero") ~ "Democrat",
        str_detect(sponsor, "Delegate Adams") ~ "Democrat",
        str_detect(sponsor, "Delegate Addison") ~ "Republican",
        str_detect(sponsor, "Delegate Allen") ~ "Democrat",
        str_detect(sponsor, "Delegate Alston") ~ "Democrat",
        str_detect(sponsor, "Delegate Anderton") ~ "Republican",
        str_detect(sponsor, "Delegate Arentz") ~ "Republican",
        str_detect(sponsor, "Delegate Arikan") ~ "Republican",
        str_detect(sponsor, "Delegate Attar") ~ "Democrat",
        str_detect(sponsor, "Delegate Atterbeary") ~ "Republican",
        str_detect(sponsor, "Delegate Bagnall") ~ "Democrat",
        str_detect(sponsor, "Delegate Baker") ~ "Republican",
        str_detect(sponsor, "Delegate Barnes") ~ "Democrat",
        str_detect(sponsor, "Delegate Bartlett") ~ "Democrat",
        str_detect(sponsor, "Delegate Bhandari") ~ "Democrat",
        str_detect(sponsor, "Delegate Boafo") ~ "Democrat",
        str_detect(sponsor, "Delegate Bouchat") ~ "Republican",
        str_detect(sponsor, "Delegate Boyce") ~ "Democrat",
        str_detect(sponsor, "Delegate Buckel") ~ "Republican",
        str_detect(sponsor, "Delegate Cardin") ~ "Democrat",
        str_detect(sponsor, "Delegate Chang") ~ "Democrat",
        str_detect(sponsor, "Delegate Charkoudian") ~ "Democrat",
        str_detect(sponsor, "Delegate Chisholm") ~ "Republican",
        str_detect(sponsor, "Delegate Ciliberti") ~ "Republican",
        str_detect(sponsor, "Delegate Clippinger") ~ "Democrat",
        str_detect(sponsor, "Delegate Conaway") ~ "Democrat",
        str_detect(sponsor, "Delegate Crosby") ~ "Democrat",
        str_detect(sponsor, "Delegate Crutchfield") ~ "Democrat",
        str_detect(sponsor, "Delegate Cullison") ~ "Democrat",
        str_detect(sponsor, "Delegate Davis") ~ "Democrat",
        str_detect(sponsor, "Delegate Ebersole") ~ "Democrat",
        str_detect(sponsor, "Delegate Edelson") ~ "Democrat",
        str_detect(sponsor, "Delegate Embry") ~ "Democrat",
        str_detect(sponsor, "Delegate Fair") ~ "Democrat",
        str_detect(sponsor, "Delegate Feldmark") ~ "Democrat",
        str_detect(sponsor, "Delegate Fennell") ~ "Democrat",
        str_detect(sponsor, "Delegate Fisher") ~ "Republican",
        str_detect(sponsor, "Delegate Foley") ~ "Democrat",
        str_detect(sponsor, "Delegate Forbes") ~ "Democrat",
        str_detect(sponsor, "Delegate Fraser-Hidalgo") ~ "Democrat",
        str_detect(sponsor, "Delegate Ghrist") ~ "Republican",
        str_detect(sponsor, "Delegate Grammer") ~ "Republican",
        str_detect(sponsor, "Delegate Griffith") ~ "Republican",
        str_detect(sponsor, "Delegate Grossman") ~ "Democrat",
        str_detect(sponsor, "Delegate Guyton") ~ "Democrat",
        str_detect(sponsor, "Delegate Guzzone") ~ "Democrat",
        str_detect(sponsor, "Delegate Harris") ~ "Democrat",
        str_detect(sponsor, "Delegate Harrison") ~ "Democrat",
        str_detect(sponsor, "Delegate Hartman") ~ "Republican",
        str_detect(sponsor, "Delegate Healey") ~ "Democrat",
        str_detect(sponsor, "Delegate Henson") ~ "Democrat",
        str_detect(sponsor, "Delegate Hill") ~ "Democrat",
        str_detect(sponsor, "Delegate Hinebaugh") ~ "Republican",
        str_detect(sponsor, "Delegate Holmes") ~ "Democrat",
        str_detect(sponsor, "Delegate Hornberger") ~ "Republican",
        str_detect(sponsor, "Delegate Howard") ~ "Republican",
        str_detect(sponsor, "Delegate Hutchinson") ~ "Republican",
        str_detect(sponsor, "Delegate Ivey") ~ "Democrat",
        str_detect(sponsor, "Delegate Jackson") ~ "Democrat",
        str_detect(sponsor, "Delegate Jacobs") ~ "Republican",
        str_detect(sponsor, "Delegate Johnson, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Johnson, S.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, D.") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaiser") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaufman") ~ "Democrat",
        str_detect(sponsor, "Delegate Kerr") ~ "Democrat",
        str_detect(sponsor, "Delegate Kipke") ~ "Republican",
        str_detect(sponsor, "Delegate Korman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lehman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, R.") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, R.") ~ "Republican",
        str_detect(sponsor, "Delegate Lopez") ~ "Democrat",
        str_detect(sponsor, "Delegate Love") ~ "Democrat",
        str_detect(sponsor, "Delegate Mangione") ~ "Republican",
        str_detect(sponsor, "Delegate Martinez") ~ "Democrat",
        str_detect(sponsor, "Delegate McCaskill") ~ "Democrat",
        str_detect(sponsor, "Delegate McComas") ~ "Republican",
        str_detect(sponsor, "Delegate Metzgar") ~ "Republican",
        str_detect(sponsor, "Delegate Miller") ~ "Republican",
        str_detect(sponsor, "Delegate Mireku-North") ~ "Democrat",
        str_detect(sponsor, "Delegate Moon") ~ "Democrat",
        str_detect(sponsor, "Delegate Morgan, M.") ~ "Republican",
        str_detect(sponsor, "Delegate Morgan, T.") ~ "Republican",
        str_detect(sponsor, "Delegate Munoz") ~ "Republican",
        str_detect(sponsor, "Delegate Nawrocki") ~ "Republican",
        str_detect(sponsor, "Delegate Otto") ~ "Republican",
        str_detect(sponsor, "Delegate Palakovich Carr") ~ "Democrat",
        str_detect(sponsor, "Delegate Pasteur") ~ "Democrat",
        str_detect(sponsor, "Delegate Patterson") ~ "Democrat",
        str_detect(sponsor, "Delegate Pena-Melnyk") ~ "Democrat",
        str_detect(sponsor, "Delegate Phillips") ~ "Democrat",
        str_detect(sponsor, "Delegate Pippy") ~ "Republican",
        str_detect(sponsor, "Delegate Pruski") ~ "Democrat",
        str_detect(sponsor, "Delegate Qi") ~ "Democrat",
        str_detect(sponsor, "Delegate Queen") ~ "Democrat",
        str_detect(sponsor, "Delegate Reilly") ~ "Republican",
        str_detect(sponsor, "Delegate Roberson") ~ "Democrat",
        str_detect(sponsor, "Delegate Roberts") ~ "Democrat",
        str_detect(sponsor, "Delegate Rogers") ~ "Democrat",
        str_detect(sponsor, "Delegate Rose") ~ "Republican",
        str_detect(sponsor, "Delegate Rosenberg") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruff") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruth") ~ "Democrat",
        str_detect(sponsor, "Delegate Sample-Hughes") ~ "Democrat",
        str_detect(sponsor, "Delegate Schmidt") ~ "Republican",
        str_detect(sponsor, "Delegate Shetty") ~ "Democrat",
        str_detect(sponsor, "Delegate Simmons") ~ "Democrat",
        str_detect(sponsor, "Delegate Simpson") ~ "Democrat",
        str_detect(sponsor, "Delegate Smith") ~ "Democrat",
        str_detect(sponsor, "Delegate Solomon") ~ "Democrat",
        str_detect(sponsor, "Delegate Spiegel") ~ "Democrat",
        str_detect(sponsor, "Delegate Stein") ~ "Democrat",
        str_detect(sponsor, "Delegate Stewart") ~ "Democrat",
        str_detect(sponsor, "Delegate Stonko") ~ "Republican",
        str_detect(sponsor, "Delegate Szeliga") ~ "Republican",
        str_detect(sponsor, "Delegate Taveras") ~ "Democrat",
        str_detect(sponsor, "Delegate Taylor") ~ "Democrat",
        str_detect(sponsor, "Delegate Terrasa") ~ "Democrat",
        str_detect(sponsor, "Delegate Toles") ~ "Democrat",
        str_detect(sponsor, "Delegate Tomlinson") ~ "Republican",
        str_detect(sponsor, "Delegate Valderrama") ~ "Democrat",
        str_detect(sponsor, "Delegate Valentine") ~ "Republican",
        str_detect(sponsor, "Delegate Vogel") ~ "Democrat",
        str_detect(sponsor, "Delegate Watson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wells") ~ "Democrat",
        str_detect(sponsor, "Delegate White Holland") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilkins") ~ "Democrat",
        str_detect(sponsor, "Delegate Williams") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wims") ~ "Democrat",
        str_detect(sponsor, "Delegate Wivell") ~ "Republican",
        str_detect(sponsor, "Delegate Wolek") ~ "Democrat",
        str_detect(sponsor, "Delegate Woods") ~ "Democrat",
        str_detect(sponsor, "Delegate Wu") ~ "Democrat",
        str_detect(sponsor, "Delegate Young") ~ "Democrat",
        str_detect(sponsor, "Delegate Ziegler") ~ "Democrat",      
        str_detect(sponsor, "President") ~ "Democrat",      
        str_detect(sponsor, "Senator Augustine") ~ "Democrat",
        str_detect(sponsor, "Senator Bailey") ~ "Republican",
        str_detect(sponsor, "Senator Beidle") ~ "Democrat",
        str_detect(sponsor, "Senator Benson") ~ "Democrat",
        str_detect(sponsor, "Senator Brooks") ~ "Democrat",
        str_detect(sponsor, "Senator Carozza") ~ "Republican",
        str_detect(sponsor, "Senator Carter") ~ "Democrat",
        str_detect(sponsor, "Senator Charles") ~ "Democrat",
        str_detect(sponsor, "Senator Corderman") ~ "Republican",
        str_detect(sponsor, "Senator Elfreth") ~ "Democrat",
        str_detect(sponsor, "Senator Ellis") ~ "Democrat",
        str_detect(sponsor, "Senator Feldman") ~ "Democrat",
        str_detect(sponsor, "Senator Ferguson") ~ "Democrat",
        str_detect(sponsor, "Senator Folden") ~ "Republican",
        str_detect(sponsor, "Senator Gallion") ~ "Republican",
        str_detect(sponsor, "Senator Gile") ~ "Democrat",
        str_detect(sponsor, "Senator Guzzone") ~ "Democrat",
        str_detect(sponsor, "Senator Hayes") ~ "Democrat",
        str_detect(sponsor, "Senator Hershey") ~ "Republican",
        str_detect(sponsor, "Senator Hester") ~ "Democrat",
        str_detect(sponsor, "Senator Hettleman") ~ "Democrat",
        str_detect(sponsor, "Senator Jackson") ~ "Democrat",
        str_detect(sponsor, "Senator James") ~ "Democrat",
        str_detect(sponsor, "Senator Jennings") ~ "Republican",
        str_detect(sponsor, "Senator Kagan") ~ "Democrat",
        str_detect(sponsor, "Senator Kelly") ~ "Democrat",
        str_detect(sponsor, "Senator King") ~ "Democrat",
        str_detect(sponsor, "Senator Klausmeier") ~ "Democrat",
        str_detect(sponsor, "Senator Kramer") ~ "Democrat",
        str_detect(sponsor, "Senator Lam") ~ "Democrat",
        str_detect(sponsor, "Senator Lewis Young") ~ "Democrat",
        str_detect(sponsor, "Senator Mautz") ~ "Republican",
        str_detect(sponsor, "Senator McCray") ~ "Democrat",
        str_detect(sponsor, "Senator McKay") ~ "Republican",
        str_detect(sponsor, "Senator Muse") ~ "Democrat",
        str_detect(sponsor, "Senator Ready") ~ "Republican",
        str_detect(sponsor, "Senator Rosapepe") ~ "Democrat",
        str_detect(sponsor, "Senator Salling") ~ "Republican",
        str_detect(sponsor, "Senator Simonaire") ~ "Republican",
        str_detect(sponsor, "Senator Smith") ~ "Democrat",
        str_detect(sponsor, "Senator Sydnor") ~ "Democrat",
        str_detect(sponsor, "Senator Waldstreicher") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, A.") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, M.") ~ "Democrat",
        str_detect(sponsor, "Senator Watson") ~ "Democrat",
        str_detect(sponsor, "Senator West") ~ "Republican",
        str_detect(sponsor, "Senator Zucker") ~ "Democrat",
        str_detect(sponsor, "Senators") ~ "Other",
        str_detect(sponsor, "Delegation") ~ "Other",
        str_detect(sponsor, "Speaker") ~ "Democrat",
        .default = "Other"
      ))

#FOR 2023
republican_bills_2023 <- republican_bills_2023 %>% 
  mutate(
    sponsor_party = case_when(
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Budget and Taxation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Economic Matters Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Education, Energy, and the Environment Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Environment and Transportation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Finance Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Health and Government Operations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judicial Proceedings Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judiciary Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Ways and Means Committee") ~ "Democrat",
        str_detect(sponsor, "Delegate Acevero") ~ "Democrat",
        str_detect(sponsor, "Delegate Adams") ~ "Democrat",
        str_detect(sponsor, "Delegate Addison") ~ "Republican",
        str_detect(sponsor, "Delegate Allen") ~ "Democrat",
        str_detect(sponsor, "Delegate Alston") ~ "Democrat",
        str_detect(sponsor, "Delegate Amprey") ~ "Democrat",
        str_detect(sponsor, "Delegate Arentz") ~ "Republican",
        str_detect(sponsor, "Delegate Arikan") ~ "Republican",
        str_detect(sponsor, "Delegate Attar") ~ "Democrat",
        str_detect(sponsor, "Delegate Atterbeary") ~ "Republican",
        str_detect(sponsor, "Delegate Bagnall") ~ "Democrat",
        str_detect(sponsor, "Delegate Barnes, B.") ~ "Democrat",
        str_detect(sponsor, "Delegate Barnes, D.") ~ "Democrat",
        str_detect(sponsor, "Delegate Bartlett") ~ "Democrat",
        str_detect(sponsor, "Delegate Barve") ~ "Democrat",
        str_detect(sponsor, "Delegate Bhandari") ~ "Democrat",
        str_detect(sponsor, "Delegate Boafo") ~ "Democrat",
        str_detect(sponsor, "Delegate Bouchat") ~ "Republican",
        str_detect(sponsor, "Delegate Boyce") ~ "Democrat",
        str_detect(sponsor, "Delegate Bridges") ~ "Democrat",
        str_detect(sponsor, "Delegate Buckel") ~ "Republican",
        str_detect(sponsor, "Delegate Cardin") ~ "Democrat",
        str_detect(sponsor, "Delegate Chang") ~ "Democrat",
        str_detect(sponsor, "Delegate Charkoudian") ~ "Democrat",
        str_detect(sponsor, "Delegate Charles") ~ "Democrat",
        str_detect(sponsor, "Delegate Chisholm") ~ "Republican",
        str_detect(sponsor, "Delegate Ciliberti") ~ "Republican",
        str_detect(sponsor, "Delegate Clippinger") ~ "Democrat",
        str_detect(sponsor, "Delegate Conaway") ~ "Democrat",
        str_detect(sponsor, "Delegate Crosby") ~ "Democrat",
        str_detect(sponsor, "Delegate Crutchfield") ~ "Democrat",
        str_detect(sponsor, "Delegate Cullison") ~ "Democrat",
        str_detect(sponsor, "Delegate Davis") ~ "Democrat",
        str_detect(sponsor, "Delegate Ebersole") ~ "Democrat",
        str_detect(sponsor, "Delegate Edelson") ~ "Democrat",
        str_detect(sponsor, "Delegate Embry") ~ "Democrat",
        str_detect(sponsor, "Delegate Fair") ~ "Democrat",
        str_detect(sponsor, "Delegate Feldmark") ~ "Democrat",
        str_detect(sponsor, "Delegate Fennell") ~ "Democrat",
        str_detect(sponsor, "Delegate Fisher") ~ "Republican",
        str_detect(sponsor, "Delegate Foley") ~ "Democrat",
        str_detect(sponsor, "Delegate Forbes") ~ "Democrat",
        str_detect(sponsor, "Delegate Fraser-Hidalgo") ~ "Democrat",
        str_detect(sponsor, "Delegate Ghrist") ~ "Republican",
        str_detect(sponsor, "Delegate Grammer") ~ "Republican",
        str_detect(sponsor, "Delegate Griffith") ~ "Republican",
        str_detect(sponsor, "Delegate Grossman") ~ "Democrat",
        str_detect(sponsor, "Delegate Guyton") ~ "Democrat",
        str_detect(sponsor, "Delegate Guzzone") ~ "Democrat",
        str_detect(sponsor, "Delegate Harris") ~ "Democrat",
        str_detect(sponsor, "Delegate Harrison") ~ "Democrat",
        str_detect(sponsor, "Delegate Hartman") ~ "Republican",
        str_detect(sponsor, "Delegate Healey") ~ "Democrat",
        str_detect(sponsor, "Delegate Henson") ~ "Democrat",
        str_detect(sponsor, "Delegate Hill") ~ "Democrat",
        str_detect(sponsor, "Delegate Hinebaugh") ~ "Republican",
        str_detect(sponsor, "Delegate Holmes") ~ "Democrat",
        str_detect(sponsor, "Delegate Hornberger") ~ "Republican",
        str_detect(sponsor, "Delegate Howard") ~ "Republican",
        str_detect(sponsor, "Delegate Hutchinson") ~ "Republican",
        str_detect(sponsor, "Delegate Ivey") ~ "Democrat",
        str_detect(sponsor, "Delegate Jackson") ~ "Democrat",
        str_detect(sponsor, "Delegate Jacobs") ~ "Republican",
        str_detect(sponsor, "Delegate Johnson, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Johnson, S.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, D.") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaiser") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaufman") ~ "Democrat",
        str_detect(sponsor, "Delegate Kelly") ~ "Democrat",
        str_detect(sponsor, "Delegate Kerr") ~ "Democrat",
        str_detect(sponsor, "Delegate Kipke") ~ "Republican",
        str_detect(sponsor, "Delegate Korman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lehman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, R.") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, R.") ~ "Republican",
        str_detect(sponsor, "Delegate Lopez") ~ "Democrat",
        str_detect(sponsor, "Delegate Love") ~ "Democrat",
        str_detect(sponsor, "Delegate Mangione") ~ "Republican",
        str_detect(sponsor, "Delegate Martinez") ~ "Democrat",
        str_detect(sponsor, "Delegate McCaskill") ~ "Democrat",
        str_detect(sponsor, "Delegate McComas") ~ "Republican",
        str_detect(sponsor, "Delegate Metzgar") ~ "Republican",
        str_detect(sponsor, "Delegate Miller") ~ "Republican",
        str_detect(sponsor, "Delegate Mireku-North") ~ "Democrat",
        str_detect(sponsor, "Delegate Moon") ~ "Democrat",
        str_detect(sponsor, "Delegate Morgan, M.") ~ "Republican",
        str_detect(sponsor, "Delegate Morgan, T.") ~ "Republican",
        str_detect(sponsor, "Delegate Munoz") ~ "Republican",
        str_detect(sponsor, "Delegate Nawrocki") ~ "Republican",
        str_detect(sponsor, "Delegate Otto") ~ "Republican",
        str_detect(sponsor, "Delegate Palakovich Carr") ~ "Democrat",
        str_detect(sponsor, "Delegate Pasteur") ~ "Democrat",
        str_detect(sponsor, "Delegate Patterson") ~ "Democrat",
        str_detect(sponsor, "Delegate Pena-Melnyk") ~ "Democrat",
        str_detect(sponsor, "Delegate Phillips") ~ "Democrat",
        str_detect(sponsor, "Delegate Pippy") ~ "Republican",
        str_detect(sponsor, "Delegate Pruski") ~ "Democrat",
        str_detect(sponsor, "Delegate Qi") ~ "Democrat",
        str_detect(sponsor, "Delegate Queen") ~ "Democrat",
        str_detect(sponsor, "Delegate Reilly") ~ "Republican",
        str_detect(sponsor, "Delegate Reznik") ~ "Democrat",
        str_detect(sponsor, "Delegate Rogers") ~ "Democrat",
        str_detect(sponsor, "Delegate Rose") ~ "Republican",
        str_detect(sponsor, "Delegate Rosenberg") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruth") ~ "Democrat",
        str_detect(sponsor, "Delegate Sample-Hughes") ~ "Democrat",
        str_detect(sponsor, "Delegate Schmidt") ~ "Republican",
        str_detect(sponsor, "Delegate Shetty") ~ "Democrat",
        str_detect(sponsor, "Delegate Simmons") ~ "Democrat",
        str_detect(sponsor, "Delegate Simpson") ~ "Democrat",
        str_detect(sponsor, "Delegate Smith") ~ "Democrat",
        str_detect(sponsor, "Delegate Solomon") ~ "Democrat",
        str_detect(sponsor, "Delegate Stein") ~ "Democrat",
        str_detect(sponsor, "Delegate Stewart") ~ "Democrat",
        str_detect(sponsor, "Delegate Szeliga") ~ "Republican",
        str_detect(sponsor, "Delegate Taveras") ~ "Democrat",
        str_detect(sponsor, "Delegate Taylor") ~ "Democrat",
        str_detect(sponsor, "Delegate Terrasa") ~ "Democrat",
        str_detect(sponsor, "Delegate Toles") ~ "Democrat",
        str_detect(sponsor, "Delegate Tomlinson") ~ "Republican",
        str_detect(sponsor, "Delegate Turner") ~ "Democrat",
        str_detect(sponsor, "Delegate Valderrama") ~ "Democrat",
        str_detect(sponsor, "Delegate Valentine") ~ "Republican",
        str_detect(sponsor, "Delegate Vogel") ~ "Democrat",
        str_detect(sponsor, "Delegate Washington") ~ "Democrat",
        str_detect(sponsor, "Delegate Watson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wells") ~ "Democrat",
        str_detect(sponsor, "Delegate White") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilkins") ~ "Democrat",
        str_detect(sponsor, "Delegate Williams") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wivell") ~ "Republican",
        str_detect(sponsor, "Delegate Woods") ~ "Democrat",
        str_detect(sponsor, "Delegate Wu") ~ "Democrat",
        str_detect(sponsor, "Delegate Young") ~ "Democrat",
        str_detect(sponsor, "Delegate Ziegler") ~ "Democrat",      
        str_detect(sponsor, "President") ~ "Democrat",      
        str_detect(sponsor, "Senator Augustine") ~ "Democrat",
        str_detect(sponsor, "Senator Bailey") ~ "Republican",
        str_detect(sponsor, "Senator Beidle") ~ "Democrat",
        str_detect(sponsor, "Senator Benson") ~ "Democrat",
        str_detect(sponsor, "Senator Brooks") ~ "Democrat",
        str_detect(sponsor, "Senator Carozza") ~ "Republican",
        str_detect(sponsor, "Senator Carter") ~ "Democrat",
        str_detect(sponsor, "Senator Corderman") ~ "Republican",
        str_detect(sponsor, "Senator Elfreth") ~ "Democrat",
        str_detect(sponsor, "Senator Ellis") ~ "Democrat",
        str_detect(sponsor, "Senator Feldman") ~ "Democrat",
        str_detect(sponsor, "Senator Ferguson") ~ "Democrat",
        str_detect(sponsor, "Senator Folden") ~ "Republican",
        str_detect(sponsor, "Senator Gallion") ~ "Republican",
        str_detect(sponsor, "Senator Gile") ~ "Democrat",
        str_detect(sponsor, "Senator Griffith") ~ "Democrat",
        str_detect(sponsor, "Senator Guzzone") ~ "Democrat",
        str_detect(sponsor, "Senator Hayes") ~ "Democrat",
        str_detect(sponsor, "Senator Hershey") ~ "Republican",
        str_detect(sponsor, "Senator Hester") ~ "Democrat",
        str_detect(sponsor, "Senator Hettleman") ~ "Democrat",
        str_detect(sponsor, "Senator Jackson") ~ "Democrat",
        str_detect(sponsor, "Senator James") ~ "Democrat",
        str_detect(sponsor, "Senator Jennings") ~ "Republican",
        str_detect(sponsor, "Senator Kagan") ~ "Democrat",
        str_detect(sponsor, "Senator Kelly") ~ "Democrat",
        str_detect(sponsor, "Senator King") ~ "Democrat",
        str_detect(sponsor, "Senator Klausmeier") ~ "Democrat",
        str_detect(sponsor, "Senator Kramer") ~ "Democrat",
        str_detect(sponsor, "Senator Lam") ~ "Democrat",
        str_detect(sponsor, "Senator Lee") ~ "Democrat",
        str_detect(sponsor, "Senator Lewis Young") ~ "Democrat",
        str_detect(sponsor, "Senator Mautz") ~ "Republican",
        str_detect(sponsor, "Senator McCray") ~ "Democrat",
        str_detect(sponsor, "Senator McKay") ~ "Republican",
        str_detect(sponsor, "Senator Muse") ~ "Democrat",
        str_detect(sponsor, "Senator Pinsky") ~ "Democrat",
        str_detect(sponsor, "Senator Ready") ~ "Republican",
        str_detect(sponsor, "Senator Rosapepe") ~ "Democrat",
        str_detect(sponsor, "Senator Salling") ~ "Republican",
        str_detect(sponsor, "Senator Simonaire") ~ "Republican",
        str_detect(sponsor, "Senator Smith") ~ "Democrat",
        str_detect(sponsor, "Senator Sydnor") ~ "Democrat",
        str_detect(sponsor, "Senator Waldstreicher") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, A.") ~ "Democrat",
        str_detect(sponsor, "Senator Washington, M.") ~ "Democrat",
        str_detect(sponsor, "Senator Watson") ~ "Democrat",
        str_detect(sponsor, "Senator West") ~ "Republican",
        str_detect(sponsor, "Senator Zucker") ~ "Democrat",
        str_detect(sponsor, "Senators") ~ "Other",
        str_detect(sponsor, "Delegation") ~ "Other",
        str_detect(sponsor, "Speaker") ~ "Democrat",
        .default = "Other"
      ))


#FOR 2022
republican_bills_2022 <- republican_bills_2022 %>% 
  mutate(
    sponsor_party = case_when(
        str_detect(sponsor, "Chair, Appropriations Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Budget and Taxation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Economic Matters Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Education, Health, and Environmental Affairs Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Environment and Transportation Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Finance Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judicial Proceedings Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Judiciary Committee") ~ "Democrat",
        str_detect(sponsor, "Chair, Ways and Means Committee") ~ "Democrat",
        str_detect(sponsor, "Delegate Acevero") ~ "Democrat",
        str_detect(sponsor, "Delegate Adams") ~ "Democrat",
        str_detect(sponsor, "Delegate Amprey") ~ "Democrat",
        str_detect(sponsor, "Delegate Anderson") ~ "Democrat",
        str_detect(sponsor, "Delegate Anderton") ~ "Republican",
        str_detect(sponsor, "Delegate Arentz") ~ "Republican",
        str_detect(sponsor, "Delegate Arikan") ~ "Republican",
        str_detect(sponsor, "Delegate Attar") ~ "Democrat",
        str_detect(sponsor, "Delegate Atterbeary") ~ "Republican",
        str_detect(sponsor, "Delegate Bagnall") ~ "Democrat",
        str_detect(sponsor, "Delegate Barnes, B.") ~ "Democrat",
        str_detect(sponsor, "Delegate Barnes, D.") ~ "Democrat",
        str_detect(sponsor, "Delegate Bartlett") ~ "Democrat",
        str_detect(sponsor, "Delegate Barve") ~ "Democrat",
        str_detect(sponsor, "Delegate Beitzel") ~ "Republican",
        str_detect(sponsor, "Delegate Belcastro") ~ "Democrat",
        str_detect(sponsor, "Delegate Bhandari") ~ "Democrat",
        str_detect(sponsor, "Delegate Boteler") ~ "Republican",
        str_detect(sponsor, "Delegate Boyce") ~ "Democrat",
        str_detect(sponsor, "Delegate Branch, C.") ~ "Democrat",
        str_detect(sponsor, "Delegate Branch, T.") ~ "Democrat",
        str_detect(sponsor, "Delegate Bridges") ~ "Democrat",
        str_detect(sponsor, "Delegate Brooks") ~ "Democrat",
        str_detect(sponsor, "Delegate Buckel") ~ "Republican",
        str_detect(sponsor, "Delegate Cardin") ~ "Democrat",
        str_detect(sponsor, "Delegate Carey") ~ "Democrat",
        str_detect(sponsor, "Delegate Carr") ~ "Democrat",
        str_detect(sponsor, "Delegate Chang") ~ "Democrat",
        str_detect(sponsor, "Delegate Charkoudian") ~ "Democrat",
        str_detect(sponsor, "Delegate Charles") ~ "Democrat",
        str_detect(sponsor, "Delegate Chisholm") ~ "Republican",
        str_detect(sponsor, "Delegate Ciliberti") ~ "Republican",
        str_detect(sponsor, "Delegate Clark") ~ "Republican",
        str_detect(sponsor, "Delegate Clippinger") ~ "Democrat",
        str_detect(sponsor, "Delegate Cox") ~ "Republican",
        str_detect(sponsor, "Delegate Crosby") ~ "Democrat",
        str_detect(sponsor, "Delegate Crutchfield") ~ "Democrat",
        str_detect(sponsor, "Delegate Cullison") ~ "Democrat",
        str_detect(sponsor, "Delegate Davis") ~ "Democrat",
        str_detect(sponsor, "Delegate Ebersole") ~ "Democrat",
        str_detect(sponsor, "Delegate Feldmark") ~ "Democrat",
        str_detect(sponsor, "Delegate Fennell") ~ "Democrat",
        str_detect(sponsor, "Delegate Fisher, M.") ~ "Republican",
        str_detect(sponsor, "Delegate Fisher, W.") ~ "Democrat",
        str_detect(sponsor, "Delegate Foley") ~ "Democrat",
        str_detect(sponsor, "Delegate Forbes") ~ "Democrat",
        str_detect(sponsor, "Delegate Fraser-Hidalgo") ~ "Democrat",
        str_detect(sponsor, "Delegate Ghrist") ~ "Republican",
        str_detect(sponsor, "Delegate Gilchrist") ~ "Republican",
        str_detect(sponsor, "Delegate Grammer") ~ "Republican",
        str_detect(sponsor, "Delegate Griffith") ~ "Republican",
        str_detect(sponsor, "Delegate Guyton") ~ "Democrat",
        str_detect(sponsor, "Delegate Harrison") ~ "Democrat",
        str_detect(sponsor, "Delegate Hartman") ~ "Republican",
        str_detect(sponsor, "Delegate Healey") ~ "Democrat",
        str_detect(sponsor, "Delegate Henson") ~ "Democrat",
        str_detect(sponsor, "Delegate Hill") ~ "Democrat",
        str_detect(sponsor, "Delegate Holmes") ~ "Democrat",
        str_detect(sponsor, "Delegate Hornberger") ~ "Republican",
        str_detect(sponsor, "Delegate Howard") ~ "Republican",
        str_detect(sponsor, "Delegate Impallaria") ~ "Republican",
        str_detect(sponsor, "Delegate Ivey") ~ "Democrat",
        str_detect(sponsor, "Delegate Jackson") ~ "Democrat",
        str_detect(sponsor, "Delegate Jacobs") ~ "Republican",
        str_detect(sponsor, "Delegate Jalisi") ~ "Democrat",
        str_detect(sponsor, "Delegate Johnson") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, A.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, D.") ~ "Democrat",
        str_detect(sponsor, "Delegate Jones, R.") ~ "Democrat",
        str_detect(sponsor, "Delegate Kaiser") ~ "Democrat",
        str_detect(sponsor, "Delegate Kelly") ~ "Democrat",
        str_detect(sponsor, "Delegate Kerr") ~ "Democrat",
        str_detect(sponsor, "Delegate Kipke") ~ "Republican",
        str_detect(sponsor, "Delegate Kittleman") ~ "Republican",
        str_detect(sponsor, "Delegate Korman") ~ "Democrat",
        str_detect(sponsor, "Delegate Krebs") ~ "Republican",
        str_detect(sponsor, "Delegate Krimm") ~ "Democrat",
        str_detect(sponsor, "Delegate Landis") ~ "Democrat",
        str_detect(sponsor, "Delegate Lehman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, J.") ~ "Democrat",
        str_detect(sponsor, "Delegate Lewis, R.") ~ "Democrat",
        str_detect(sponsor, "Delegate Lierman") ~ "Democrat",
        str_detect(sponsor, "Delegate Lisanti") ~ "Democrat",
        str_detect(sponsor, "Delegate Long, R.") ~ "Republican",
        str_detect(sponsor, "Delegate Lopez") ~ "Democrat",
        str_detect(sponsor, "Delegate Love") ~ "Democrat",
        str_detect(sponsor, "Delegate Luedtke") ~ "Democrat",
        str_detect(sponsor, "Delegate Mangione") ~ "Republican",
        str_detect(sponsor, "Delegate Mautz") ~ "Republican",
        str_detect(sponsor, "Delegate McComas") ~ "Republican",
        str_detect(sponsor, "Delegate McIntosh") ~ "Democrat",
        str_detect(sponsor, "Delegate McKay") ~ "Republican",
        str_detect(sponsor, "Delegate Metzgar") ~ "Republican",
        str_detect(sponsor, "Delegate Moon") ~ "Democrat",
        str_detect(sponsor, "Delegate Morgan") ~ "Republican",
        str_detect(sponsor, "Delegate Munoz") ~ "Republican",
        str_detect(sponsor, "Delegate Novotny") ~ "Republican",
        str_detect(sponsor, "Delegate Otto") ~ "Republican",
        str_detect(sponsor, "Delegate Palakovich Carr") ~ "Democrat",
        str_detect(sponsor, "Delegate Parrott") ~ "Republican",
        str_detect(sponsor, "Delegate Patterson") ~ "Democrat",
        str_detect(sponsor, "Delegate Pena-Melnyk") ~ "Democrat",
        str_detect(sponsor, "Delegate Pendergrass") ~ "Democrat",
        str_detect(sponsor, "Delegate Pippy") ~ "Republican",
        str_detect(sponsor, "Delegate Prettyman") ~ "Democrat",
        str_detect(sponsor, "Delegate Proctor") ~ "Democrat",
        str_detect(sponsor, "Delegate Qi") ~ "Democrat",
        str_detect(sponsor, "Delegate Queen") ~ "Democrat",
        str_detect(sponsor, "Delegate Reilly") ~ "Republican",
        str_detect(sponsor, "Delegate Reznik") ~ "Democrat",
        str_detect(sponsor, "Delegate Rogers") ~ "Democrat",
        str_detect(sponsor, "Delegate Rose") ~ "Republican",
        str_detect(sponsor, "Delegate Rosenberg") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruth") ~ "Democrat",
        str_detect(sponsor, "Delegate Ruth") ~ "Democrat",
        str_detect(sponsor, "Delegate Saab") ~ "Republican",
        str_detect(sponsor, "Delegate Sample-Hughes") ~ "Democrat",
        str_detect(sponsor, "Delegate Shetty") ~ "Democrat",
        str_detect(sponsor, "Delegate Shoemaker") ~ "Republican",
        str_detect(sponsor, "Delegate Smith") ~ "Democrat",
        str_detect(sponsor, "Delegate Solomon") ~ "Democrat",
        str_detect(sponsor, "Delegate Stein") ~ "Democrat",
        str_detect(sponsor, "Delegate Stewart") ~ "Democrat",
        str_detect(sponsor, "Delegate Szeliga") ~ "Republican",
        str_detect(sponsor, "Delegate Terrasa") ~ "Democrat",
        str_detect(sponsor, "Delegate Thiam") ~ "Republican",
        str_detect(sponsor, "Delegate Turner") ~ "Democrat",
        str_detect(sponsor, "Delegate Valderrama") ~ "Democrat",
        str_detect(sponsor, "Delegate Valentino-Smith") ~ "Republican",
        str_detect(sponsor, "Delegate Walker") ~ "Democrat",
        str_detect(sponsor, "Delegate Washington") ~ "Democrat",
        str_detect(sponsor, "Delegate Watson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wells") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilkins") ~ "Democrat",
        str_detect(sponsor, "Delegate Williams") ~ "Democrat",
        str_detect(sponsor, "Delegate Wilson") ~ "Democrat",
        str_detect(sponsor, "Delegate Wivell") ~ "Republican",
        str_detect(sponsor, "Delegate Woods") ~ "Democrat",
        str_detect(sponsor, "Delegate Wu") ~ "Democrat",
        str_detect(sponsor, "Delegate Delegate Young, K.") ~ "Democrat",
        str_detect(sponsor, "Delegate Delegate Young, P.") ~ "Democrat",
        str_detect(sponsor, "President") ~ "Democrat",      
        str_detect(sponsor, "Senator Augustine") ~ "Democrat",
        str_detect(sponsor, "Senator Bailey") ~ "Republican",
        str_detect(sponsor, "Senator Beidle") ~ "Democrat",
        str_detect(sponsor, "Senator Benson") ~ "Democrat",
        str_detect(sponsor, "Senator Carozza") ~ "Republican",
        str_detect(sponsor, "Senator Carter") ~ "Democrat",
        str_detect(sponsor, "Senator Cassilly") ~ "Republican",
        str_detect(sponsor, "Senator Corderman") ~ "Republican",
        str_detect(sponsor, "Senator Eckardt") ~ "Republican",
        str_detect(sponsor, "Senator Edwards") ~ "Republican",
        str_detect(sponsor, "Senator Elfreth") ~ "Democrat",
        str_detect(sponsor, "Senator Ellis") ~ "Democrat",
        str_detect(sponsor, "Senator Feldman") ~ "Democrat",
        str_detect(sponsor, "Senator Ferguson") ~ "Democrat",
        str_detect(sponsor, "Senator Gallion") ~ "Republican",
        str_detect(sponsor, "Senator Griffith") ~ "Democrat",
        str_detect(sponsor, "Senator Guzzone") ~ "Democrat",
        str_detect(sponsor, "Senator Hayes") ~ "Democrat",
        str_detect(sponsor, "Senator Hershey") ~ "Republican",
        str_detect(sponsor, "Senator Hester") ~ "Democrat",
        str_detect(sponsor, "Senator Hettleman") ~ "Democrat",
        str_detect(sponsor, "Senator Hough") ~ "Republican",
        str_detect(sponsor, "Senator Jackson") ~ "Democrat",
        str_detect(sponsor, "Senator Jennings") ~ "Republican",
        str_detect(sponsor, "Senator Kagan") ~ "Democrat",
        str_detect(sponsor, "Senator Kelley") ~ "Democrat",
        str_detect(sponsor, "Senator King") ~ "Democrat",
        str_detect(sponsor, "Senator Klausmeier") ~ "Democrat",
        str_detect(sponsor, "Senator Kramer") ~ "Democrat",
        str_detect(sponsor, "Senator Lam") ~ "Democrat",
        str_detect(sponsor, "Senator Lee") ~ "Democrat",
        str_detect(sponsor, "Senator McCray") ~ "Democrat",
        str_detect(sponsor, "Senator McKay") ~ "Republican",
        str_detect(sponsor, "Senator Patterson") ~ "Democrat",
        str_detect(sponsor, "Senator Pinsky") ~ "Democrat",
        str_detect(sponsor, "Senator Ready") ~ "Republican",
        str_detect(sponsor, "Senator Reilly") ~ "Republican",
        str_detect(sponsor, "Senator Rosapepe") ~ "Democrat",
        str_detect(sponsor, "Senator Salling") ~ "Republican",
        str_detect(sponsor, "Senator Simonaire") ~ "Republican",
        str_detect(sponsor, "Senator Smith") ~ "Democrat",
        str_detect(sponsor, "Senator Sydnor") ~ "Democrat",
        str_detect(sponsor, "Senator Waldstreicher") ~ "Democrat",
        str_detect(sponsor, "Senator Washington") ~ "Democrat",
        str_detect(sponsor, "Senator Watson") ~ "Democrat",
        str_detect(sponsor, "Senator West") ~ "Republican",
        str_detect(sponsor, "Senator Young") ~ "Democrat",
        str_detect(sponsor, "Senator Zucker") ~ "Democrat",
        str_detect(sponsor, "Senators") ~ "Other",
        str_detect(sponsor, "Delegation") ~ "Other",
        str_detect(sponsor, "Speaker") ~ "Democrat",
        .default = "Other"
      ))
```



```{r}
#add column with the year and then stack the entire dataset

republican_bills_2022 <- republican_bills_2022 %>% 
  mutate(year = 2022)

republican_bills_2023 <- republican_bills_2023 %>% 
  mutate(year = 2023)

republican_bills_2024 <- republican_bills_2024 %>% 
  mutate(year = 2024)

republican_bills_2025 <- republican_bills_2025 %>% 
  mutate(year = 2025)

republican_bills_2026 <- republican_bills_2026 %>% 
  mutate(year = 2026)

all_republican_bills <- republican_bills_2022 %>% bind_rows(republican_bills_2023, republican_bills_2024, republican_bills_2025, republican_bills_2026)
```



```{r}
#add column to show cross-filed status

all_republican_bills <- all_republican_bills %>% 
  mutate(
    cross_filed = case_when(
        str_detect(bill_chapter_cross_chapter, "\\(") ~ "Cross-filed",
        .default = "Not cross-filed",
  ))
```



```{r}
bills_by_filing_status <- all_republican_bills %>% 
  group_by(cross_filed) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

write.csv(bills_by_filing_status, file = "data/bills_by_filing_status.csv", row.names = TRUE)
```



```{r}
#should i consider filing status in this?

bills_by_sponsor_party <- all_republican_bills %>% 
  group_by(sponsor_party) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

bills_by_sponsor_party <- bills_by_sponsor_party %>% 
  mutate(
    percent = count/(sum(count))*100
  )

write.csv(bills_by_sponsor_party, file = "data/bills_by_sponsor_party.csv", row.names = TRUE)
```



```{r}
#filter by bills passed

all_republican_bills <- all_republican_bills %>% 
  mutate(
    pass_status = case_when(
        str_detect(current_status, "Passed Enrolled") ~ "Passed",
        str_detect(current_status, "Returned Passed") ~ "Passed",
        str_detect(current_status, "Special Order") ~ "Passed",
        str_detect(current_status, "Approved by the Governor") ~ "Passed",
        .default = "Not passed",
  ))

```



```{r}
bills_by_party_passing <- all_republican_bills %>% 
  group_by(sponsor_party, pass_status) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

bills_by_party_passing <- bills_by_party_passing %>% 
  mutate(
    percent = count/(sum(count))*100
  )

write.csv(bills_by_party_passing, file = "data/bills_by_party_passing.csv", row.names = TRUE)
```



```{r}
bills_by_party_passing_by_year <- all_republican_bills %>% 
  group_by(year, sponsor_party, pass_status) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

bills_by_party_passing <- bills_by_party_passing %>% 
  mutate(
    percent = count/(sum(count))*100
  )

write.csv(bills_by_party_passing_by_year, file = "data/bills_by_party_passing_by_year.csv", row.names = TRUE)
```